### ISSUE TITLE
nbstripout --uninstall fails

### ISSUE THREAD

**Issue by AllanLRH** [kynan/nbstripout#40]
```
$ nbstripout --uninstall
Traceback (most recent call last):
  File "/lscr_paper/allan/miniconda3/envs/msth/bin/nbstripout", line 11, in <module>
    sys.exit(main())
  File "/lscr_paper/allan/miniconda3/envs/msth/lib/python3.5/site-packages/nbstripout.py", line 248, in main
    sys.exit(uninstall(args.attributes))
  File "/lscr_paper/allan/miniconda3/envs/msth/lib/python3.5/site-packages/nbstripout.py", line 191, in uninstall
    f.write(''.join(lines))
ValueError: I/O operation on closed file.
```
I've added a few comments to the file, and they disappeared along with the line added by `nbstripout --install`, so I guess the file was overwritten with a blank file.

The problem happens on Linux running Bash and on OS X running Zsh.

I'm using the Anaconda Python Distribution, Python 3.5.2, inside a conda environment, and I installed using `pip install nbstripout`.

**Comment by kynan** [comment]
Thanks for the report! I was able to reproduce this on Anaconda Python 3.5.2, will push a fix.

Not sure why it fails though: the attributes file was opened twice, once for reading and once for writing.
