### ISSUE TITLE
nbstripout install fails

### ISSUE THREAD

**Issue by michaelaye** [kynan/nbstripout#5]
Am I using it wrong?

```bash
(py35)
klay6683 at macd2860 in ~PYTHONPATH/planet4 (master●)
$ nbstripout install
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/py35/bin/nbstripout", line 9, in <module>
    load_entry_point('nbstripout==0.2.0', 'console_scripts', 'nbstripout')()
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/site-packages/nbstripout-0.2.0-py3.5.egg/nbstripout.py", line 127, in main
    sys.exit(install())
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/site-packages/nbstripout-0.2.0-py3.5.egg/nbstripout.py", line 111, in install
    attrfile = path.join(git_dir, 'info', 'attributes')
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
(py35)
```

**Comment by michaelaye** [comment]
It seems to be a Python2/3 problem, `git_dir` might need a decode() call in P3?
